#BeginMacro(calc)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * ((-1,0) + (0,-1) + (0,1) + (1,0) - 4 * (0,0))))
#EndMacro

#BeginMacro(calc-up)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * (         (0,-1) + (0,1) + (1,0) - 4 * (0,0))))
#EndMacro

#BeginMacro(calc-dn)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * ((-1,0) + (0,-1) + (0,1)         - 4 * (0,0))))
#EndMacro

#BeginMacro(calc-lf)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * ((-1,0) +          (0,1) + (1,0) - 4 * (0,0))))
#EndMacro

#BeginMacro(calc-rg)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * ((-1,0) + (0,-1)         + (1,0) - 4 * (0,0))))
#EndMacro

#BeginMacro(calc-ul)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * (                  (0,1) + (1,0) - 4 * (0,0))))
#EndMacro

#BeginMacro(calc-ur)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * (         (0,-1)         + (1,0) - 4 * (0,0))))
#EndMacro

#BeginMacro(calc-bl)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * ((-1,0)          + (0,1)         - 4 * (0,0))))
#EndMacro

#BeginMacro(calc-br)
trunc((1.1 * (0,0) * ( 1 - (0,0) / 100)) + trunc(0.12 * ((-1,0) + (0,-1)                 - 4 * (0,0))))
#EndMacro

